# Generated by Django 5.2 on 2025-04-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_delete_todoitem_ipcameraimage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_detection', models.BooleanField(default=False)),
            ],
        ),
    ]
