# Generated by Django 5.2 on 2025-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_camerasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='face_detection',
            field=models.BooleanField(default=False),
        ),
    ]
