# Generated by Django 5.2 on 2025-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_camerasettings_face_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='frame_process_interval',
            field=models.FloatField(default=0.5),
        ),
    ]
