# Generated by Django 5.2 on 2025-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_camerasettings_frame_process_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasettings',
            name='face_detection_db_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camerasettings',
            name='movement_detection_db_save',
            field=models.BooleanField(default=False),
        ),
    ]
